language=zh_CN
squashfs=/lib/live/mount/medium/live/filesystem.squashfs
timezone=Asia/Shanghai
HOST_name=container-$(uuidgen -r | awk -F'-' '{print $1}')
ROOT_passwd=U1mail2me
USER_name=container
USER_passwd=U1mail2me
power=yes
swap_size=1G
sys_size=y
