#!/bin/bash
_partition() {

    _info "Listing disk and partitions"

    # Select disk to use
    until [[ ${_disk} =~ ^(sd|hd)[a-z]{1}$ ]]; do
        fdisk -l
        _prompt "Enter disk to use:" "(ex: sda)"
        read -r _disk
    done

    if [[ ${_disk} =~ ^(sd|hd)[a-z]{1}$ ]]; then
		export part_order=(0 1 2 3 4)
	else
		export part_order=(p0 p1 p2 p3 p4)
	fi

	until [[ ! -z ${method} ]];do
		_info "Choose which installation method to use:"
		echo -e "\t 1. partition automation"
		echo -e "\t 2. lvm based volume"
		echo -e "\t 3. zfs based volume"

		_prompt "Enter which to choose:" "(ex: 1)"
		read -r _choose
		case ${_choose} in 
			1)
				_partition_auto
				export method="auto"
				;;
			2)
				_partition_lvm
				export method="lvm"
				;;
			3)
				_partition_zfs
				export method="zfs"
				;;
			4)
				_partition_manual
				export method="manual"
				;;
			*)
				_error "please choose supported method number"
				;;
		esac
	done

	# Export 
	export _disk
}

_create_boot(){
    # Create MBR or GPT Table
    fdisk -l /dev/${_disk}
    _note "WARNING! This will erase the entire drive."
    _confirm "Setting ${part_table} partition table on /dev/${_disk}"
    if [[ ${confirm} == "y" ]]; then
        wipefs -fa /dev/${_disk}
        printf ${part_code}"\nw" | fdisk /dev/${_disk}
        partprobe /dev/${_disk}
    else
        _error "aborted by user! HDD dedicated is required."
    fi
    unset confirm

    # BOOT partition size
    boot_size="512M"

    # Create BOOT partition on /dev/xxx1
    _info "Setting boot of ${boot_size} on /dev/${_disk}${part_order[1]}"
    printf "n\n${part_type}\n\n+${boot_size}\nw" | fdisk /dev/${_disk}
    partprobe /dev/${_disk} && sleep 1s
    yes | _check wipefs -fa /dev/${_disk}${part_order[1]}
    yes | _check mkfs.${boot_filesystem} /dev/${_disk}${part_order[1]}

}
_create_swap(){
    # SWAP partition size
    until [[ ${swap_size} =~ ^[0-9]{1,3}(M|G){1} \
    || ${swap_size,,} == "y" ]]; do
        _note "Partition size {M,G} [default: 2G]"
        _prompt "Swap partition size:" "default [y]"
        read -r swap_size
    done
    if [[ ${swap_size,,} == "y" ]]; then
        swap_size="2G"
    fi

    # Create SWAP partition on /dev/xxx2
    _info "Setting Swap of ${swap_size} on /dev/${_disk}${part_order[2]}"
    printf "n\n${part_type}\n\n+${swap_size}\nw" | fdisk /dev/${_disk}
    partprobe /dev/${_disk} && sleep 1s
    yes | _check wipefs -fa /dev/${_disk}${part_order[2]}
    yes | _check mkswap /dev/${_disk}${part_order[2]}
}

_partition_auto(){
	_create_boot
	_create_swap
    # SYSTEM partiton size
    until [[ ${sys_size} =~ ^[0-9]{1,3}(G|T|P){1} \
    || ${sys_size,,} == "y" ]]; do
        _note "Partition size {G,T,P} [default: free space]"
        _prompt "System partition size:" "default [y]"
        read -r sys_size
    done
    if [[ ${sys_size,,} == "y" ]]; then
        part_size="free space"
        sys_size=""
	else
        part_size="${sys_size}"
        sys_size="+"${sys_size}
    fi

    # Create SYSTEM partition on /dev/xxx3
    _info "Setting System of ${sys_size} on /dev/${_disk}${part_order[3]}"
    printf "n\n${part_type}\n\n${sys_size}\nw" | fdisk /dev/${_disk}
    partprobe /dev/${_disk} && sleep 1s
    yes | _check wipefs -fa /dev/${_disk}${part_order[3]}
    yes | _check mkfs.ext4 /dev/${_disk}${part_order[3]}
}

_partition_zfs(){
	_create_boot
	modprobe zfs
    _info "Setting System on /dev/${_disk}${part_order[2]}"
    printf "n\n${part_type}\n\n\nw" | fdisk /dev/${_disk}
    # Create zfs on /dev/xxx2
    yes | _check wipefs -fa /dev/${_disk}${part_order[2]}
	_info "Creating zfs pool on /dev/${_disk}${part_order[2]}"
	_check zpool create -f zroot /dev/${_disk}${part_order[2]}
	_check zfs create -o mountpoint=none zroot/ROOT
	# cannot mount to / now
	zfs create -o mountpoint=/ zroot/ROOT/default || true
	_check zpool set bootfs=zroot/ROOT/default zroot

	_info "Export and import zfs pool"
	_check zpool export zroot
	_check zpool import -d /dev/disk/by-id -R /mnt zroot
	zpool set cachefile=/etc/zfs/zpool.cache zroot
	install -Dm644 /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache
}

_partition_lvm(){
	_create_boot
	# Create root lvm volume
    until [[ ${swap_size} =~ ^[0-9]{1,3}(M|G){1} \
    || ${swap_size,,} == "y" ]]; do
        _note "Partition size {M,G} [default: 2G]"
        _prompt "Swap partition size:" "default [y]"
        read -r swap_size
    done
    if [[ ${swap_size,,} == "y" ]]; then
        swap_size="2G"
    fi

	_info "Creating physical root volume on /dev/${_disk}${part_order[2]}"
    yes | _check wipefs -fa /dev/${_disk}${part_order[2]}
	lvm pvcreate /dev/${_disk}${part_order[2]}
	lvm vgcreate lvm /dev/${_disk}${part_order[2]}
    _info "Creating logical swapspace "
	lvm lvcreate -L "${swap_size}" -n swap lvm 
	_info "Creating logical root volume: lvroot"
	lvm lvcreate -l 100%FREE -n lvroot lvm
    _info "Setting System on  /dev/mapper/root"
    partprobe /dev/${_disk} && sleep 1s
    yes | _check mkfs.ext4 /dev/mapper/root
}
